# This is a config for E2B sandbox template.
# You can use template ID (r9a6k0bj1q8ib9mf0jmy) or template name (vibe-nextjs-test-23) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-test-23") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-23") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-23')

team_id = "37385b90-ce10-40e4-a5ee-af66a9baffd8"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-23"
template_id = "r9a6k0bj1q8ib9mf0jmy"
